### ISSUE TITLE
Day-ahead forecast lead time and horizon

### ISSUE THREAD

**Issue by xy3134** [PERFORM-Forecasts/documentation#6]
Hello,

The day-ahead forecasts for load has 12-hour-ahead lead time, while the day-ahead forecasts for wind and solar (site-level) have 36-hour-ahead lead time. Is there a reason, or I misunderstood the meaning of lead time?

Also, the wind and solar forecasts have only 24-hour horizon, while in the README, it says that day-head forecasts will have a 48 hour horizon. Are the forecasts with the 48-hour horizon not published yet?

Thanks,
Xinshuo Yang

**Comment by fzhang-WZ** [comment]
Hi Xinshuo,

The lead time should be 12-hour-ahead lead time. The issue time for both DA wind and solar needs to be +1 day. The files will be updated with the correct issue time. Thanks for pointing this out. 

We only have time series with the length of 8760 for both wind and solar ensembles due to the way the ensembles were originally processed. That means currently the wind and solar forecasts only have 24-hour horizon. We will publish the 48-hour horizon forecasts once we finish processing the 2nd-day DA ensembles. Sorry for the confusion. 

Best,
Flora

**Comment by MRossol** [comment]
@xy3134 Day-ahead forecast lead time and horizon: lead time has been corrected. It will take longer time to extend the horizon.

**Comment by xy3134** [comment]
@fzhang-WZ  @MRossol Thanks for the update.

**Comment by MRossol** [comment]
@xy3134 , this should be fixed in today data update
